# Guided Capstone Step 6. Documentation

**The Data Science Method**  


1.   Problem Identification 

2.   Data Wrangling 
  
3.   Exploratory Data Analysis 
 
4.   Pre-processing and Training Data Development

5.  Modeling

6.   **Documentation**
  * Review the Results
  * Finalize Code 
  * Finalize Documentation
  * Create a Project Report 
  * Create a Slide Deck for the Executive Audience

In this guided capstone we are going to revisit many of the actions we took in the previous guided capstone steps. This gives you the opportunity to practice the code you wrote to solve the questions in step 4 and 5. 

**<font color='teal'> Start by loading the necessary packages and printing out our current working directory just to confirm we are in the correct project directory. </font>**

In [1]:
import os
import pandas as pd
from collections import Counter
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import explained_variance_score
from sklearn.metrics import mean_absolute_error
from sklearn import linear_model
from sklearn.metrics import explained_variance_score,mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn import preprocessing


In [2]:
os.listdir()

['.DS_Store',
 '.ipynb_checkpoints',
 'data',
 'figures',
 'formatted_for_final',
 'formatted_for_final.csv',
 'GuidedCapstoneStep3HL-Copy1.ipynb',
 'GuidedCapstoneStep3HL.ipynb',
 'GuidedCapstoneStep4 and step5HL-Copy1.ipynb',
 'GuidedCapstoneStep4 and step5HL.ipynb',
 'GuidedCapstoneStep6HL.ipynb',
 'models',
 'Notebook_steptwo.ipynb',
 'step2_output.csv',
 'step3_2_output.csv',
 'step3_df_output.csv',
 'step3_output.csv',
 'step4 and 5.ipynb',
 'updated_ski_data.csv',
 '__MACOSX']

In [3]:
df=pd.read_csv('step3_df_output.csv',index_col=0)

In [4]:
df.head()

Name    state  summit_elev  vertical_drop  base_elev  trams  \
0       Alyeska Resort   Alaska         3939           2500        250      1   
1  Eaglecrest Ski Area   Alaska         2600           1540       1200      0   
2     Hilltop Ski Area   Alaska         2090            294       1796      0   
3     Arizona Snowbowl  Arizona        11500           2300       9200      0   
4  Sunrise Park Resort  Arizona        11100           1800       9200      0   

   fastEight  fastSixes  fastQuads  quad  ...  SkiableTerrain_ac  \
0        0.0          0          2     2  ...             1610.0   
1        0.0          0          0     0  ...              640.0   
2        0.0          0          0     0  ...               30.0   
3        0.0          1          0     2  ...              777.0   
4        NaN          0          1     2  ...              800.0   

   Snow Making_ac  daysOpenLastYear  yearsOpen  averageSnowfall  AdultWeekday  \
0           113.0             150.0       60.0            669.0          65.0   
1            60.0              45.0       44.0            350.0          47.0   
2            30.0             150.0       36.0             69.0          30.0   
3           104.0             122.0       81.0            260.0          89.0   
4            80.0             115.0       49.0            250.0          74.0   

   AdultWeekend  projectedDaysOpen  NightSkiing_ac  clusters  
0          85.0              150.0           550.0         1  
1          53.0               90.0             NaN         1  
2          34.0              152.0            30.0         1  
3          89.0              122.0             NaN         0  
4          78.0              104.0            80.0         0  

[5 rows x 27 columns]

## Fit Models with Training Dataset

**<font color='teal'> Using sklearn fit the model you chose in Guided Capstone 5 on your training dataset. This includes: creating dummy features for states if you need them, scaling the data,and creating train and test splits before fitting the chosen model.Also, remember to generate a model performance score(MAE, or explained variance) based on the testing hold-out data set.</font>**

#### Best Model 

In [5]:
df=pd.get_dummies(df, columns=['state']) #this creates dummies for state, however we will not be using state functions and it will be removed later
df=df.fillna(0)
df.head()

Name  summit_elev  vertical_drop  base_elev  trams  \
0       Alyeska Resort         3939           2500        250      1   
1  Eaglecrest Ski Area         2600           1540       1200      0   
2     Hilltop Ski Area         2090            294       1796      0   
3     Arizona Snowbowl        11500           2300       9200      0   
4  Sunrise Park Resort        11100           1800       9200      0   

   fastEight  fastSixes  fastQuads  quad  triple  ...  state_Rhode Island  \
0        0.0          0          2     2       0  ...                   0   
1        0.0          0          0     0       0  ...                   0   
2        0.0          0          0     0       1  ...                   0   
3        0.0          1          0     2       2  ...                   0   
4        0.0          0          1     2       3  ...                   0   

   state_South Dakota  state_Tennessee  state_Utah  state_Vermont  \
0                   0                0           0              0   
1                   0                0           0              0   
2                   0                0           0              0   
3                   0                0           0              0   
4                   0                0           0              0   

   state_Virginia  state_Washington  state_West Virginia  state_Wisconsin  \
0               0                 0                    0                0   
1               0                 0                    0                0   
2               0                 0                    0                0   
3               0                 0                    0                0   
4               0                 0                    0                0   

   state_Wyoming  
0              0  
1              0  
2              0  
3              0  
4              0  

[5 rows x 61 columns]

In [6]:
df = df.loc[:, ~df.columns.str.startswith('state')] #removing state features

In [7]:
#sklearn and other packages were imported from the top
# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
x = df.drop(['Name','AdultWeekend'], axis=1)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df.AdultWeekend 

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = StandardScaler().fit(x)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled=scaler.transform(x) 

In [8]:

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=1)

In [9]:
#setting the model:
lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

In [10]:
y_pred = model.predict(X_test)

In [11]:
#explained variance is here, it should be between 1 and 0
explained_variance_score(y_test, y_pred)

0.9240208791564122

In [12]:
#Mean Absolute Error
mean_absolute_error(y_test, y_pred)

5.492663035346577

In [13]:
#intercept and list of coeficients:
print(lm.intercept_)
print(lm.coef_)

64.06180964776385
[-1.36670054e+01  4.89543804e+00  1.04865034e+01 -3.02031585e-01
 -8.83168515e-02  4.25018788e-01  7.00191389e-01  1.55939455e+00
  1.44785872e+00  3.77383252e-01 -1.30931122e+00  6.93442971e-01
 -1.48289775e+00 -2.04288799e-01 -1.65870322e-01 -4.04754006e-01
 -1.59614668e-03  1.01605478e+00  2.90103177e-01 -1.58251646e+00
  1.99983708e+01 -3.76790155e-01  5.16848706e-01 -9.45255710e-01]


In [14]:
cofdf=pd.DataFrame(abs(lm.coef_), x.columns, columns=['Coefficient'])
cofdf.iloc[:10]

Coefficient
summit_elev      13.667005
vertical_drop     4.895438
base_elev        10.486503
trams             0.302032
fastEight         0.088317
fastSixes         0.425019
fastQuads         0.700191
quad              1.559395
triple            1.447859
double            0.377383

In [15]:
X_scaled

array([[-1.75024298e-01,  1.35728620e+00, -1.00372860e+00, ...,
         1.04347142e+00,  5.28388759e+00, -7.80868809e-02],
       [-5.34017876e-01,  3.42945226e-01, -6.98497431e-01, ...,
        -1.04716512e+00, -6.09611897e-01, -7.80868809e-02],
       [-6.70751800e-01, -9.73584832e-01, -5.07005035e-01, ...,
         1.11315930e+00, -2.88148289e-01, -7.80868809e-02],
       ...,
       [ 8.62276787e-01,  3.75699987e-01,  9.19870352e-01, ...,
         1.02684975e-01,  5.69088000e-01,  1.53245504e+00],
       [ 1.35961292e+00, -2.38187625e-01,  1.74270932e+00, ...,
        -9.90324405e-16, -6.09611897e-01, -1.68862880e+00],
       [ 1.31591169e+00, -1.21961055e-01,  1.61483353e+00, ...,
        -9.90324405e-16, -6.09611897e-01, -1.68862880e+00]])

## Review the results 

**<font color='teal'> Now, let's predict the Big Mountain Weekend price with our model in order to provide a recommendation to our managers on how to price the `AdultWeekend` lift ticket. First we need to find the row for Big Mountain resort in our data using string contains or string matching.</font>**

In [16]:
resort=df[df['Name'].str.contains('Whitefish Mountain')]

In [17]:
resort['AdultWeekend']

151    81.0
Name: AdultWeekend, dtype: float64

In [18]:
resort

Name  summit_elev  vertical_drop  base_elev  trams  \
151  Whitefish Mountain Resort         6817           2353       4464      0   

     fastEight  fastSixes  fastQuads  quad  triple  ...  SkiableTerrain_ac  \
151        0.0          0          3     2       6  ...             3000.0   

     Snow Making_ac  daysOpenLastYear  yearsOpen  averageSnowfall  \
151           600.0             123.0       72.0            333.0   

     AdultWeekday  AdultWeekend  projectedDaysOpen  NightSkiing_ac  clusters  
151          81.0          81.0              123.0           600.0         2  

[1 rows x 26 columns]

**<font color='teal'> Prepare the Big Mountain resort data row as you did in the model fitting stage.</font>**

In [19]:
# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
x2 = resort.drop(['Name','AdultWeekend'], axis=1)
#x2=x2.values

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df[df['Name'].str.contains('Whitefish Mountain')].AdultWeekend 

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler2 = StandardScaler().fit(x2)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled2=scaler.transform(x2) 
#X_transformed = scaler.fit_transform(x2[:, np.newaxis])
#= scaler.transform(X.reshape(1, -1))
#.fit_transform([np.float32(data)])

In [37]:
# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_scaled2, test_size=0.25, random_state=1)

ValueError: With n_samples=1, test_size=0.25 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

In [92]:
X_scaled2

array([[ 0.596584  ,  1.20196524,  0.3502126 , -0.30893969, -0.05513178,
        -0.2840776 ,  0.90289472,  0.81409101,  2.78349171, -1.01161941,
         0.18418936,  0.99023179,  1.23415417,  0.76679853,  1.62949472,
         1.25487649,  1.75663992,  0.24535374,  0.07647692,  1.10855403,
         0.96733304,  0.10268497,  5.81966027,  1.53245504]])

In [93]:
x2

array([[6.817e+03, 2.353e+03, 4.464e+03, 0.000e+00, 0.000e+00, 0.000e+00,
        3.000e+00, 2.000e+00, 6.000e+00, 0.000e+00, 3.000e+00, 1.400e+01,
        1.050e+02, 4.000e+00, 3.300e+00, 3.000e+03, 6.000e+02, 1.230e+02,
        7.200e+01, 3.330e+02, 8.100e+01, 1.230e+02, 6.000e+02, 2.000e+00]])

**<font color='teal'> Predict the Big Mountain resort `Adult Weekend` price and print it out.</font>** This is our expected price to present to management. Based on our model given the characteristics of the resort in comparison to other ski resorts and their unique characteristics.

In [28]:
y_pred = model.predict(X_test)
y_pred

array([ 57.08331462,  86.00324261,  82.91684599,  78.41755136,
        66.8382916 ,  82.07597329,  38.04774716,  47.81577912,
        88.93990428,  85.50976197,  52.04753796,  80.91440802,
        52.93827425,  65.78922107,  63.44544647,  88.33125936,
        37.54644558,  77.88144788,  63.30503815,  43.45615872,
       109.24447454,  37.3490337 ,  53.87813754,  50.14279201,
        50.59306928,  58.63601028,  66.59823445,  69.94213396,
        63.67959786,  64.67597486,  38.71004245,  53.7286682 ,
        78.54099522,  57.18176482,  75.56138072,  54.26883741,
        25.32160627,  28.22359457,  55.20307411,  38.97482004,
        49.85533418,  63.18983927,  88.44599655,  66.736654  ,
        69.01094032,  52.78967048,  64.65606387, 166.60543691,
        30.740555  ,  64.89746613,  62.98019871,  60.3616955 ,
        53.83439269,  47.00008875,  61.08815   ,  41.89326082,
        88.71741142,  31.351776  , 120.59528219, 116.20550833,
        57.86826724,  55.87827248,  39.79604729,  86.20

**<font color='teal'> Print the Big Mountain resort actual `Adult Weekend` price.</font>**

**<font color='teal'> As part of reviewing the results it is an important step to generate figures to visualize the data story. We can use the clusters we added to our data frame to create scatter plots for visualizing the Adult Weekend values compared to other characteristics. Run the example below to get you started and build two or three more figures to include in your data story telling.</font>**

In [0]:
#plt.scatter(df['summit_elev'], df['vertical_drop'], c=df['clusters'], s=50, cmap='viridis', label ='clusters')
#plt.scatter(ac['summit_elev'], ac['vertical_drop'], c='black', s=100)
#plt.xlabel('summit_elev')
#plt.ylabel('vertical_drop')
#plt.title('summit_elev by vertical_drop by cluster')
#plt.savefig('figures/fig1.png',bbox_inches='tight')

## Finalize Code

 Making sure our code is well organized and easy to follow is an important step. This is the time where you need to review the notebooks and Python scripts you've created and clean them up so they are easy to follow and succinct in nature. Addtionally, we will also save our final model as a callable object using Pickle for future use in a data pipeline. Pickle is a module that serializes (and de-serializes) Python objects so that they can become executable objects like functions. It's used extensively in production environments where machine learning models are deployed on an industrial scale!**<font color='teal'> Run the example code below to save out your callable model. Notice that we save it in the models folder we created in our previous guided capstone step.</font>** 

In [0]:
#import pickle
#s = pickle.dumps(model)
#from joblib import dump, load
#dump(model, 'models/regression_model_adultweekend.joblib') 

## Finalize Documentation

For model documentation, we want to save the model performance metrics as well as the features included in the final model. You could also save the model perfomance metrics and coefficients fo the other models you tried in case you want to refer to them later. **<font color='teal'> Create a dataframe containing the coefficients and the model performance metrics and save it out as a csv file, then upload it to your github repository.</font>** 